### PR TITLE
transform SiCard value from 0 to Empty in edit competitor widget

### PR DESCRIPTION
**Pull request by otahirs**
before
Screenshot from 2021-12-06 11-32-55

after
Screenshot from 2021-12-06 11-31-32

### CODE REVIEW

**Comment by arnost00** [comment]
Why is 0 value problem ?
And why only in this one dialog ?
In other cases we show 0. In relay runners edit, tableviews, reports and more.

**Comment by otahirs** [comment]
> Why is 0 value problem ? 
it needs to be manually deleted every time

> why only in this one dialog ?
I have not run into inconveniences enywhere else, I also did not look how the value is stored and moved in other places so in order not to break anything I only updated the look in edit field.

**Comment by arnost00** [comment]
> I have not run into inconveniences enywhere else, I also did not look how the value is stored and moved in other places so in order not to break anything I only updated the look in edit field.

Relays? [Add unregistred runner](https://github.com/Quick-Event/quickbox/issues/665#issuecomment-955700517)

**Comment by otahirs** [comment]
form was not using SiIDEdit class, but a simple QSpinBox. I changed it to SiIdEdit as this is used in the edit competitor dialog and now the appearance is the same.

**Comment by fvacek** [comment]
it seems good to me, IMO it doesn't matter if an invalid SI is `0` or empty string as well.

**Pull request merged**
