### PR TITLE
Relay import start numbers

### PR DESCRIPTION
**Pull request by arnost00**
Add Import of start numbers (bibs) from CSV for relays.

### CODE REVIEW

**Comment by arnost00** [comment]
Testing will take place this week on data for MCR Š&D (Organizer is TZL)

**Comment by fvacek** [comment]
Can you prepare this also for `qe3` branch please?

**Comment by arnost00** [comment]
> Can you prepare this also for `qe3` branch please?

Yes, that's the plan.

**Comment by arnost00** [comment]
QE3 preparation branch is : [relay-import-start-numbers-qe3](https://github.com/arnost00/quickbox/tree/relay-import-start-numbers-qe3)

**Comment by arnost00** [comment]
TZL is still testing it, while preparing the MČR Š+D

**Comment by arnost00** [comment]
Version tested. App version increased.

**Comment by arnost00** [comment]
QE3 version is in PR https://github.com/Quick-Event/quickbox/pull/983

**Review by fvacek — APPROVED** [review]

**Pull request merged**
